name: CI Builds

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - run: msbuild ${{ github.event.repository.name }}.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
    - run: cp x64\Release\${{ github.event.repository.name }}.asi ./${{ github.event.repository.name }}.asi
    - run: cp .\README.md .\${{ github.event.repository.name }}_README.md
    - run: 7z a -tzip ${{ github.event.repository.name }}-run-${{ github.run_number }} ${{ github.event.repository.name }}.ini ${{ github.event.repository.name }}_README.md ${{ github.event.repository.name }}.asi
    - run: 7z a ${{ github.event.repository.name }}-run-${{ github.run_number }} assets\
